# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_books_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
