# Generated by Django 2.2.4 on 2019-08-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
