# Generated by Django 2.2.4 on 2019-08-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=20)),
                ('citydescription', models.TextField(max_length=2000)),
                ('cityyear', models.CharField(max_length=4)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghomepage.Content')),
            ],
        ),
    ]
