# Generated by Django 2.2.4 on 2019-08-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghomepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='contents',
            new_name='content',
        ),
    ]
