# Generated by Django 2.2.4 on 2019-08-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloghomepage', '0004_auto_20190828_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=2000)),
                ('playerpic', models.ImageField(default='media/images/black.jpg', upload_to='images/')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghomepage.Content')),
            ],
        ),
    ]
