# Generated by Django 2.2.4 on 2019-08-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloghomepage', '0005_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField(max_length=10000)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghomepage.Content')),
            ],
        ),
    ]
